name: flutter_atp
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  alarm: ^4.0.12
  carousel_slider: ^5.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  geolocator: ^13.0.1
  get: ^4.3.8
  google_fonts: ^6.2.1
  latlong2: ^0.9.1
  location: ^7.0.1
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.3
  sqflite: ^2.4.1
  supabase_flutter: ^2.8.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
